name: "📝 문서"
description: "필요한 문서 작성"
title: "📝 "
labels: ["📝 문서"]
projects: ["yakplus/1"]
body:
  - type: input
    id: input_name
    attributes:
      label: 📣 문서 이름
      description: 💭 문서의 이름을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: 📣 문서 작업 이유
      description: 💭 문서 작업 이유을 적어주세요
      placeholder: |
        🫧 <문서 생성 이유>
        1. <이유>
        2. <이유>
      render: ''
    validations:
      required: false
  - type: checkboxes
    id: checkboxes_list
    attributes:
      label: 📣 작성자 체크리스트
      description: 💭 작성자 체크리스트
      options:
        - label: 🔱 문서 제목을 적절하게 정하였습니까?
          required: true
        - label: 📍 타이틀에 문서 이름을 추가하였습니까?
          required: true